// Package broker is the execution-layer abstraction.
//
// Two implementations live here:
//   - paper/   — simulated execution (PaperBroker C1, fixed-fee, no slippage)
//   - binance/ — real exchange execution via LocalAgent (Phase 7)
//
// The Broker contract is intentionally minimal: PlaceOrder + Kind. Balance
// retrieval, reconciliation, and ledger persistence are the SaaS instance
// manager's job — not every broker has a sensible "GetBalances" semantic
// (paper-mode balances live in our DB, not the exchange).
package broker

import "context"

// Action constants.
const (
	ActionBUY  = "BUY"
	ActionSELL = "SELL"
)

// LotType constants — must match the strategy SDK's TradeIntent.LotType.
const (
	LotTypeDead       = "DEAD"
	LotTypeFloat      = "FLOAT"
	LotTypeColdSealed = "COLD_SEALED"
)

// TradeCommand is the broker-facing translation of a strategy's TradeIntent.
//
// `ClientOrderID` is generated by the SaaS instance manager (format:
// inst{id}-{engine}-{action}-{barTimeMs}-{seq}, see docs/00- §5.3) and is
// the canonical identifier across the whole order lifecycle. The exchange
// (or PaperBroker) echoes it back in Execution.ClientOrderID so the SaaS
// can match fills to pending rows.
type TradeCommand struct {
	ClientOrderID string
	Symbol        string
	Action        string  // BUY / SELL
	Engine        string  // strategy-defined: MACRO / MICRO / GRID / DCA / ...
	LotType       string  // DEAD / FLOAT — where new fills are bucketed
	AmountUSDT    float64 // BUY uses this
	QtyAsset      float64 // SELL uses this
	BarTimeMs     int64   // the bar this command was issued on (for audit)
}

// ExecutionStatus enumerates terminal-state and in-flight states.
const (
	StatusFilled            = "filled"
	StatusPartiallyFilled   = "partially_filled" // partial then canceled
	StatusCanceled          = "canceled"
	StatusRejected          = "rejected"
	StatusPending           = "pending"
)

// Execution is the broker's response to PlaceOrder.
//
// Paper mode always returns a terminal state immediately (filled / rejected).
// Real Binance returns a terminal state only after the LocalAgent reconciles
// the exchange order — for now (Phase 6 paper-only), we don't model that.
type Execution struct {
	ClientOrderID   string
	OrderID         string  // exchange-side ID; paper broker generates a UUID
	Status          string  // filled / partially_filled / canceled / rejected
	FilledQty       float64 // asset quantity actually executed
	FilledPriceUSDT float64 // average fill price
	FeeAmount       float64 // in FeeAsset units
	FeeAsset        string  // typically "USDT" for BUY, the symbol's base for SELL
	ExecutedAtMs    int64   // simulator wall-clock or exchange fill time
	RejectReason    string  // populated when Status != filled
}

// Broker is the execution interface.
//
// PlaceOrder is synchronous — paper executes immediately; future binance
// adapter blocks on the WS round-trip but eventually returns terminal status
// (or "pending" if it can't get one in time).
type Broker interface {
	PlaceOrder(ctx context.Context, cmd TradeCommand, currentPrice float64) (Execution, error)

	// Kind returns a stable identifier for logging / metrics ("paper-simple",
	// "paper-realistic", "binance-spot", ...).
	Kind() string
}
